[theme]
base = "dark"
primaryColor = "#00f9ff"
backgroundColor = "#0b0c10"
secondaryBackgroundColor = "#1f2833"
textColor = "#c5c6c7"
font = "monospace"

[server]
runOnSave = true

[client]
showSidebarNavigation = false
showToolbar = false
